/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLastFetchedAt' : IDL.Func([], [IDL.Int], ['query']),
  'getLatestArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getLastFetchedAt' : IDL.Func([], [IDL.Int], ['query']),
    'getLatestArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };